name: dystopia-2
channels:
  - conda-forge

dependencies:
  - python==3.7
  - pip
  - pip:
    - tensorflow==2.1.0
    - numpy
    - opencv-python
    - PyYAML
    - tqdm
    - Pillow
    - Cython
    - ipython
    - sklearn2
    - flask
    - imutils
